import type { Metadata } from "next";
import { PoppinsFont } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Droppe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={`${PoppinsFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
